### ISSUE TITLE
Players embedded on website

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#13]
Sample code for how to embed players on the Our Networks (or any other) website.

**Comment by darkdrgn2k** [comment]
I updated Video.JS and videojs-contrib-hls in hopes to be more supported across devices

Also made the  IPFS vs Traditional internet easier selection simpler and some UI feedback 
http://tomesh.org/stream/

Source
https://github.com/darkdrgn2k/ipfs-live-stream/tree/master/client/js-version-ournetworks

working on making it look better on mobile. but its 1/2 decent right now

**Comment by dcwalk** [comment]
This looks so neat! Just to make sure I'm understanding -- we'd host this on the Our Networks site (ournetworks.ca), correct?

**Comment by benhylau** [comment]
Run this on same box as ipfs-server and make URL for it.

**Comment by benhylau** [comment]
This is now merged in. Can the designer take over this ticket :)
https://github.com/tomeshnet/ipfs-live-streaming/tree/master/terraform/shared/video-player

This is for this repo only and can have its own theme and colours independent from Our Networks.

**Comment by benhylau** [comment]
Do we like these?

## `#1`
### Social Network and Cloud Network by Creative Stall from the Noun Project

![screen shot 2018-07-05 at 2 56 44 am](https://user-images.githubusercontent.com/2261308/42307157-9457fb0e-7fff-11e8-8a1c-44c7587e9215.png)

## `#2`
### teamwork and Cloud by Dinosoft Labs from the Noun Project

![screen shot 2018-07-05 at 2 57 57 am](https://user-images.githubusercontent.com/2261308/42307158-94689306-7fff-11e8-9199-88244cd394bb.png)

## `#3`
### teamwork and Cloud by Dinosoft Labs from the Noun Project

![screen shot 2018-07-05 at 2 58 39 am](https://user-images.githubusercontent.com/2261308/42307159-949e4e38-7fff-11e8-8f25-9f2348ec0c2b.png)

In all of them I would imagine icon smaller centred in a larger bounding box, and `IPFS` `HTTP` text written underneath the icon.

@garrying @Shrinks99 thoughts? Want to draw our own?

The copy here is self-contradicting:

![screen shot 2018-07-05 at 2 59 29 am](https://user-images.githubusercontent.com/2261308/42307160-94af1fec-7fff-11e8-9f77-6e80c1aa7246.png)

We also should change that graphic.

**Comment by dcwalk** [comment]
IPFS folks have some beautiful artwork, a bunch is CC, mabye something of use? (https://github.com/ipfs/artwork/)

<img width="299" alt="screen shot 2018-07-05 at 12 15 48 pm" src="https://user-images.githubusercontent.com/4692834/42335088-30ed5a0c-804d-11e8-88f1-ccd0d75690e1.png">

probably a little too far away from the look for this event tho

**Comment by benhylau** [comment]
Thanks for sharing @dcwalk I quite like them. The one you shared illustrates the peer-to-peer content quite nicely.

When looking for icons earlier, I was struggling to find two icons of the same set that show both distributed and "central cloud". Perhaps we can use what @dcwalk posted as the distributed, and the cloud server here as HTTP:

![download2](https://user-images.githubusercontent.com/2261308/42340596-7ef302ae-805e-11e8-993e-e28d7cfb2b7e.png)

The bottom right here is fun for a loading icon:

![download](https://user-images.githubusercontent.com/2261308/42340635-9fb78b22-805e-11e8-8f56-55ee46a95613.png)

As for Our Networks, can we colour theme these to be consistent with Our Networks colours?

cc. @garrying @Shrinks99

**Comment by benhylau** [comment]
All done thanks @garrying
