### ISSUE TITLE
Content for archiving

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#15]
Two sets of videos will be archived:

1. All live streamed 720p HLS chunks published as a single DVR m3u8 to ipfs end of each day (how to do this should be documented)
1. OBS will record 1080p .mp4 of each talk individually, stored on a hard disk on-site (how these get published is out of scope for this repo)

**Comment by benhylau** [comment]
We need to have someone provide a 1 TB HDD and test this. @ASoTNetworks do you have this available?

**Comment by ASoTNetworks** [comment]
I have that available and also have around 600GB of internal space.
