### ISSUE TITLE
v0.1 tag TODOs

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#29]
Since Our Networks is happening shortly, we are finalizing features so we can tag this and run a persistent cluster, then let the designers polish player UI and @ASoTNetworks stress test with his OBS on-premise set up. Here are remaining tasks before tagging:

- [x] Disable IPNS due to https://github.com/tomeshnet/ipfs-live-streaming/issues/3
- [x] Publish one-time a message on IPNS message when `ipfs-server` starts up, stating IPNS currently disabled
- [x] By default, use `/var/www/html/live.m3u8` to stream, both on `ipfs-server` and `ipfs-mirror`, the player URL should not need the `?url=live.m3u8` param
- [x] Use plain old `wget` to distribute `live.m3u8` to mirrors (since IPNS is disabled and `ipfs pubsub pub <topic> <data>` is too late to make the feature cut)
- [x] Work across IPFS restart https://github.com/tomeshnet/ipfs-live-streaming/issues/27
- [x] Work across ffmpeg restart https://github.com/tomeshnet/ipfs-live-streaming/pull/28

**Comment by benhylau** [comment]
After we ship v0.1 we need to start https://github.com/tomeshnet/ipfs-live-streaming/issues/30

**Comment by darkdrgn2k** [comment]
live.m3u8
https://github.com/tomeshnet/ipfs-live-streaming/tree/7192d1c047c69a26ba964b7f99dd910e91cf6bb7

Remove ipns publish
https://github.com/tomeshnet/ipfs-live-streaming/tree/a9ffea9bbfc47659a3ad4d4e38b38832c9c9d669

**Comment by benhylau** [comment]
@darkdrgn2k I think I also fixed the odd one where sometimes `rtmp-server` fails to provision after the ipfs.service symlink line.
