### ISSUE TITLE
Post-v0.1 testing

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#30]
There are issues not addressed in the v0.1 tag, but they are non-critical / randomly occurring cases that would benefit from being worked on off of a stable v0.1 tag. We expect these to happen over next week:

- [x] Verify streaming with conference setup for 10+ hours @ASoTNetworks 
- [x] Investigate occasional black-screen video or jitter frames after ffmpeg restart @darkdrgn2k 
- [x] Polish UI for player @Shrinks99 @garrying 
- [x] Failures after ~30 chunks when @benhylau streams the MetaMesh clip resulting in "non-monotonous dts in output stream 0:1" all over the logs
- [x] One-site testing at Mozilla @darkdrgn2k @ASoTNetworks @Shrinks99 @benhylau

**Comment by darkdrgn2k** [comment]
>  Verify streaming with conference setup for 10+ hours

I have run it for 5 hours how without any issues :+1: 

> Investigate occasional black-screen video or jitter frames after ffmpeg restart @darkdrgn2k

I'm not sure what could be causing this.  only thing i can think of is bug in ffmpeg or something to do with bad key frames.

**Comment by benhylau** [comment]
`non-monotonous dts in output stream 0:1` probably due to network issues @benhylau had, so related to https://github.com/tomeshnet/ipfs-live-streaming/issues/45 and same fix applies.
