### ISSUE TITLE
Sync call scheduling

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#4]
@darkdrgn2k @ASoTNetworks How about Wednesday night open calls every 2 weeks @[appear.in/ournetworks](https://appear.in/ournetworks)?

**Comment by ASoTNetworks** [comment]
I cannot do Wednesday nights as I am busy those nights.

**Comment by benhylau** [comment]
Monday nights starting June 11?

**Comment by ASoTNetworks** [comment]
Monday nights works fine for me.
