### ISSUE TITLE
A/V equipment list

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#5]
We can move the discussion from https://github.com/ournetworks/2018/issues/26 to here.

**Comment by Shrinks99** [comment]
# A List Of Items You Will Likely Want To Have
This is a list of items you will most likely need to live stream the conference

- Microphone(s)
  - Multiple may be required for what you want to accomplish
  - Good to have backup mics in case they break, especially for if you are doing wireless microphones!

- Microphone Cable
  - You probably want XLR cable for your XLR mics
  - Same rule of backup cables applies, you never know!

- Microphone mixer
  - Should output to whatever you require as an input on your PC

- PC
  The PC used for managing the streaming software likely needs to have the following items
  - Video capture card(s) (for camera input(s) )
  - Loads of HDD space or external drives, RAW 1080p footage is **HUGE** and if you are saving it to edit together talks to publish afterwards you will need a lot of it.  A few terrabytes should be safe, 1 hour of Cannon RAW video is ~250GB.
  - An audio input that is comparable with whatever the mixer outputs (most likely the line in on the motherboard IO but also could be a dedicated sound card if you are audiophiles
  - Two monitors (OBS or other streaming software on one monitor, other things on the other monitor, just trust me you will likely want more than one)

- Camera(s) that supports a live feed
  - You need a camera that is able to send footage to the capture card live

- A solid internet connection
  - Should be taken care of, if Mozilla doesn't have a solid internet connection I'm not sure who would

I will add more items to this list if they come up / when I think of them.  In the mean time, research begins!

**Comment by ASoTNetworks** [comment]
I would also suggest adding an live video switcher so you can switch between slide show and camera(s).

@darkdrgn2k mentioned that he will bring the VGA / Display Port / DVI to HDMI converter for connecting presenter laptops.

The audio and video data would need to go over HDMI to the computer for encoding and pushing it to the internet.

**Comment by benhylau** [comment]
@ASoTNetworks will bring one Elgato HD60 and I want to purchase a second one. One for capturing the video camera HDMI output, the other for the presenter slides.

This eliminates the need for a HDMI switch, gives us parallel streams on the OBS interface. Also serves as backup if one card breaks, we can just give up one of the views.

We want to purchase this instead of rent so we can test the whole setup ahead of time.

**Comment by ASoTNetworks** [comment]
I forgot to mention I will also bring my laptop for OBS but I think we should have another laptop on standby if something goes wrong.

**Comment by ASoTNetworks** [comment]
After doing some research apparently there are issues with the drivers that you cannot use 2 Elgatos capture card at the same time.
https://obsproject.com/forum/threads/using-two-elgatos-at-the-same-time.41208/

The solution is most likely using another brand of capture card or an hardware HDMI switch.

**Comment by darkdrgn2k** [comment]
Possible alternative is the HDPVR from hauppague

https://www.newegg.ca/Product/Product.aspx?Item=9SIAAYY5S21869&cm_re=hdpvr_2-_-15-116-086-_-Product

Also I never tried it but they do have HDMI to Component converters that would work with the HDPVR's i have

https://www.ebay.com/itm/HDMI-to-1080P-Component-Video-YPbPr-Scaler-Converter-Adapter-with-Coaxial-/253412419944

**Comment by darkdrgn2k** [comment]
Better solution would be to use a PC and an internal PCIe board like [Hauppauge Colossus](https://www.amazon.ca/Hauppauge-Colossus-Express-Internal-HD-PVR/dp/B00WMJMDG6/ref=sr_1_1?ie=UTF8&qid=1528028977&sr=8-1&keywords=hdpvr+2) and avoid the usb bottleneck.

**Comment by benhylau** [comment]
Waiting for site visit to confirm.

**Comment by benhylau** [comment]
All set!
