### ISSUE TITLE
Error running plan: 2 error(s) occurred, please help!

### ISSUE THREAD

**Issue by faint32** [tomeshnet/ipfs-live-streaming#59]
i do it following the readme, but get the error, what's the problem? thanks  very much!!!

![default](https://user-images.githubusercontent.com/4533124/47965340-cc21c100-e080-11e8-8a22-e8ab7022f836.PNG)

**Comment by darkdrgn2k** [comment]
@benhylau have any insight into this error?

@faint32 is this screenshot after a subsequent (tray again) install or the first one.
If its a subsequent did you destroy the resources created the first time?

**Comment by faint32** [comment]
@darkdrgn2k it's the first time to run it, and the client system is ubuntu 18.04, the vps of digital ocean is ubuntu too. thanks very much!!!

**Comment by benhylau** [comment]
Is it still the same error? Yes it's normal that the file is empty, it will get populated after the terraform apply completes. I am a little lost why terraform complains even though the file is there.

**Comment by benhylau** [comment]
[`value`](https://www.terraform.io/docs/providers/do/r/record.html#value) is definitely a valid (and required) attribute in a `digitalocean_record`. I wonder if newer versions of terraform changed its validation... can you:

1. First try to put `10.0.0.1` into the `rtmp_yggdrasil` and try to `terraform apply` with that.

2. If that fails, put the `10.0.0.1` directly into [here](https://github.com/tomeshnet/ipfs-live-streaming/blob/master/terraform/main.tf#L79) like this:

    ```
    resource "digitalocean_record" "publish-yggdrasil" {
      domain = "${digitalocean_domain.ipfs-live-streaming.name}"
      type   = "AAAA"
      name   = "yggdrasil.publish"
      value  = "10.0.0.1"
      ttl    = "600"
    }
    ```

Thanks for your help.

**Comment by faint32** [comment]
@benhylau i put 10.0.0.1 into the rtmp_yggdrasil and run terraform apply, and it's ok now, thanks very much!!!
