### ISSUE TITLE
Publish presentation and demo from IPFS All Hands

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#64]
Let's link the presentation video to our repo, it's a good explanation to how this works.

https://www.youtube.com/watch?v=VFsKl6UMwqM

Thoughts about the following?

1. Perhaps download from YouTube and link a IPFS pinned version of the raw file?
1. Pin the embedded player with it?
1. Crop off the rest of the call so it begins at the Live Streaming presentation?

**Comment by ASoTNetworks** [comment]
I opened a PR for this issue [here.](https://github.com/tomeshnet/ipfs-live-streaming/pull/65)

**Comment by benhylau** [comment]
Thanks @ASoTNetworks
