### ISSUE TITLE
Closed-captioning

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#7]
See: https://github.com/ournetworks/2018/issues/26#issuecomment-368278209

**Comment by ASoTNetworks** [comment]
After discussing possible ways of using live-ai close captioning service we have decided that making a "tab" or embed beside the player would be a better option.

Another option is opening a link to their interface which will have nice features like text size and colours ect.

**Comment by benhylau** [comment]
Decided not to do.
