### ISSUE TITLE
Long-term archiving of video content

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#8]

**Comment by dcwalk** [comment]
Internet Archive
IPFS/protocol folks archives (https://github.com/ipfs/archives) and asking others?

**Comment by benhylau** [comment]
@ASoTNetworks will bring 1 TB HDD and we will record in 1080p in mp4, each talk separately.

**Comment by dcwalk** [comment]
Are you documenting this stuff somewhere? 

I see the readme mentions 1 TB hard drive, but I really think it would be good to have a plan for some of the post-event stuff-- already people have asked about video, so the day of I think we need an answer for dispensation!

**Comment by benhylau** [comment]
The readme of this repo is where all the decisions about the setup is captured. I think where to put Our Networks content should be documented in Our Networks repo. A few things were talked about, including Internet Archive, ipfs, YouTube...
