### ISSUE TITLE
Presentation Buffer

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/ipfs-live-streaming#9]
_Next talk is..._

See: https://github.com/ournetworks/2018/issues/26#issuecomment-387452703

**Comment by dcwalk** [comment]
Also see: https://github.com/ournetworks/2018/issues/68, I think there might be art constraints imposed by whatever software/service is used for the schedule, so ensuring those requirements are shared back to that Our Networks issue on presentation buffers would be good 👾

**Comment by benhylau** [comment]
How will presentation buffers be mixed into both the stream and displayed on the projector screen?

**Comment by Shrinks99** [comment]
Those will be set up as OBS scenes, a quick example of how that works can be found [here](https://medium.com/go-live/getting-started-with-obs-scenes-65583da4c15d).  The presentation screen at the event should be handled separately.  Let me know what graphics need to be made and I will have a go at it!

**Comment by darkdrgn2k** [comment]
I wrote a script that will read a JSON file and update field in OBS automatically

https://github.com/darkdrgn2k/ipfs-live-stream/blob/master/obs/Buffer.py

Currently has 3 fields
Talk Title
Presenters Name
Time
![image](https://user-images.githubusercontent.com/29005789/41859598-7db6b0b2-786a-11e8-8435-ad26684a36ed.png)

Requires Python installed 
Add script in OBS under under Tools, Scripts

Python Settings requires path to python script installation
![image](https://user-images.githubusercontent.com/29005789/41859687-b1043c00-786a-11e8-816b-a5dfa053dfa5.png)

Under Scripts click the + and find the py script
![image](https://user-images.githubusercontent.com/29005789/41859722-c9ebf10e-786a-11e8-87c5-b1c85c343388.png)

Then click on it
Right side fill in the following fields (this is the name you gave it in OBS)

Text Title  - Talk Title
Text Presenter - Presenters Name
Text Time - Time the talk takes place

json_filename does not work right now so I had to hardcode the path to c:\\test\\test.json  Correct this if you with a different path
https://github.com/darkdrgn2k/ipfs-live-stream/blob/a1da7aeecf9e2e708368f84df864527abe8bd6c0/obs/Buffer.py#L137
Remember to escape with \\

Check enable.

JSON file looks as follows

```
[
   {
      "title":"Registration and coffee",
      "presenter":"Our Networks",
      "startTime":"2018-06-25 08:30",
      "endTime":"2018-06-25 09:00"
   },
   {
      "title":"Opening remarks",
      "presenter":"Our Networks",
      "startTime":"2018-06-25 9:00",
      "endTime":"2018-06-25 9:30"
   },
   {
      "title":"Wireless Toronto",
      "presenter":"Gabe Sawhney",
      "startTime":"2018-06-25 11:00",
      "endTime":"2018-06-25 12:00"
   },
   {
      "title":"test2",
      "presenter":"test3",
      "startTime":"2018-06-25 13:00",
      "endTime":"2018-06-25 14:00"
   },
   {
      "title":"test3",
      "presenter":"test4",
      "startTime":"2018-06-25 14:00",
      "endTime":"2018-06-25 15:00"
   }
]```

**Comment by darkdrgn2k** [comment]
Also,
I already wrote in "next talk" selection logic, just need to add some fields to apply to appropriate fields

**Comment by dcwalk** [comment]
Neat! Just tagging @garrying here -- can the template layout be modified to the event look? 
Also we have all the session details as a YAML file, if easy enough could you pull from that?

**Comment by Shrinks99** [comment]
@dcwalk The plan is to give the layouts styles that match the current graphics!

**Comment by garrying** [comment]
@Shrinks99 RE Between Stream Graphic: We've listed sponsors [here](https://github.com/ournetworks/2018/issues/68). At least one more will be added soon.

RE Lower Third, Slide / Presenter View: From a quick look, could we do without the cut corners for the name and talk title? We should see how this looks with one of the longer titled talks and multi-presenter sessions. Also, I'm generally in favour of making the slide view as large as possible, and moving the views closer to the edges.

**Comment by dcwalk** [comment]
Sorry, I'm not sure how I missed the earlier message @Shrinks99 

- agree with @garrying on removing the cut corners
- also would like to increase the slide view 
- could we reduce the negative space? particularly in the second one
- we've tended to use the "://" as a shorthand in branding (for instance, see the [buttons](https://github.com/ournetworks/artwork/tree/master/2018/pins)) so I'm wondering if we could do so here?
- Maybe we can just do Picture in Picture / cut out for the Speaker and Slide view?

Also agree with testing on a gnarly presentation name I think this one is a good fit: 
https://ournetworks.ca/conference/program/#community-networks,-a-perspective-from-freedom

**Comment by benhylau** [comment]
Closing this in favour of https://github.com/ournetworks/2018/issues/68
