### ISSUE TITLE
Check if __IPFS_GATEWAY_ORIGIN__ is required

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/ipfs-live-streaming#90]
Check the code to see if required anymore

**Comment by benhylau** [comment]
Looks like no
https://github.com/tomeshnet/ipfs-live-streaming/search?q=__IPFS_GATEWAY_ORIGIN__&unscoped_q=__IPFS_GATEWAY_ORIGIN__

**Comment by darkdrgn2k** [comment]
// var m3u8_ipfs = '__IPFS_GATEWAY_ORIGIN__/ipns/__IPFS_ID_ORIGIN__'; // IPNS path to m3u8 file containing IPFS content (uncomment to enable)

Seems its used for the IPNS (thats currently commented out)

**Comment by benhylau** [comment]
Removed it in https://github.com/tomeshnet/ipfs-live-streaming/pull/106/commits/14d74d82b37c28cd5de0abfa79fb52fc9fb326df
